### ISSUE TITLE
search snippets gone

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#94]
search snippets gone

**Comment by rvkennedy** [comment]
As we discussed this seems to be an issue with cross-site requests. However I'm not currently seeing it reproduce in Firefox or Chrome. Even with strict tracking protection enabled in Firefox I see the snippets.
@rbessems can you have a close look at your settings and see if anything might be relevant?

**Comment by rbessems** [comment]
```
getGraphicsAPI() from cookie: vulkan [search.html:74:13](https://openxr-tutorial.com/search.html?q=vulkan&check_keywords=yes&area=default)
getGraphicsAPI() returned: vulkan [search.html:76:11](https://openxr-tutorial.com/search.html?q=vulkan&check_keywords=yes&area=default)
getPlatform() from cookie: windows [search.html:58:13](https://openxr-tutorial.com/search.html?q=vulkan&check_keywords=yes&area=default)
getPlatform() returned: windows 2 [search.html:60:11](https://openxr-tutorial.com/search.html?q=vulkan&check_keywords=yes&area=default)
updatePlatform() = windows [search.html:132:11](https://openxr-tutorial.com/search.html?q=vulkan&check_keywords=yes&area=default)
getPlatform() returned: windows [search.html:60:11](https://openxr-tutorial.com/search.html?q=vulkan&check_keywords=yes&area=default)
getGraphicsAPI() returned: vulkan 3 [search.html:76:11](https://openxr-tutorial.com/search.html?q=vulkan&check_keywords=yes&area=default)
Uncaught (in promise) TypeError: docContent is null
    htmlToText https://openxr-tutorial.com/_static/searchtools.js:167
    makeSearchSummary https://openxr-tutorial.com/_static/searchtools.js:553
    _displayItem https://openxr-tutorial.com/_static/searchtools.js:102
7 [searchtools.js:167:35](https://openxr-tutorial.com/_static/searchtools.js)
```

​

**Comment by rbessems** [comment]
This is FF with default settings on Linux.

**Comment by rbessems** [comment]
I see the same issue with Chrome FWIW

![Screenshot from 2024-01-04 14-56-28](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/77022116/4b6b4238-e34e-44c8-88da-505e74657936)

**Comment by rvkennedy** [comment]
Does it report anything in the console?

**Comment by rbessems** [comment]
```
getGraphicsAPI() defaulted to: vulkan
search.html?q=vulkan&check_keywords=yes&area=default:76 getGraphicsAPI() returned: vulkan
search.html?q=vulkan&check_keywords=yes&area=default:55 Uncaught ReferenceError: windows is not defined
    at getPlatform (search.html?q=vulkan&check_keywords=yes&area=default:55:48)
    at updatePlatformFromURL (search.html?q=vulkan&check_keywords=yes&area=default:109:88)
    at onpageshow (search.html?q=vulkan&check_keywords=yes&area=default:350:155)
getPlatform @ search.html?q=vulkan&check_keywords=yes&area=default:55
updatePlatformFromURL @ search.html?q=vulkan&check_keywords=yes&area=default:109
onpageshow @ search.html?q=vulkan&check_keywords=yes&area=default:350
searchtools.js:97 
        
        
       GET https://openxr-tutorial.com/undefined1-introduction.html 404 (Not Found)
_displayItem @ searchtools.js:97
_displayNextItem @ searchtools.js:131
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at Object.htmlToText (searchtools.js:167:53)
    at Object.makeSearchSummary (searchtools.js:553:25)
    at searchtools.js:102:20
htmlToText @ searchtools.js:167
makeSearchSummary @ searchtools.js:553
(anonymous) @ searchtools.js:102
Promise.then (async)
_displayItem @ searchtools.js:99
_displayNextItem @ searchtools.js:131
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:97 
        
        
       GET https://openxr-tutorial.com/undefined2-setup.html 404 (Not Found)
_displayItem @ searchtools.js:97
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at Object.htmlToText (searchtools.js:167:53)
    at Object.makeSearchSummary (searchtools.js:553:25)
    at searchtools.js:102:20
htmlToText @ searchtools.js:167
makeSearchSummary @ searchtools.js:553
(anonymous) @ searchtools.js:102
Promise.then (async)
_displayItem @ searchtools.js:99
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:97 
        
        
       GET https://openxr-tutorial.com/undefined3-graphics.html 404 (Not Found)
_displayItem @ searchtools.js:97
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at Object.htmlToText (searchtools.js:167:53)
    at Object.makeSearchSummary (searchtools.js:553:25)
    at searchtools.js:102:20
htmlToText @ searchtools.js:167
makeSearchSummary @ searchtools.js:553
(anonymous) @ searchtools.js:102
Promise.then (async)
_displayItem @ searchtools.js:99
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:97 
        
        
       GET https://openxr-tutorial.com/undefined5-extensions.html 404 (Not Found)
_displayItem @ searchtools.js:97
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at Object.htmlToText (searchtools.js:167:53)
    at Object.makeSearchSummary (searchtools.js:553:25)
    at searchtools.js:102:20
htmlToText @ searchtools.js:167
makeSearchSummary @ searchtools.js:553
(anonymous) @ searchtools.js:102
Promise.then (async)
_displayItem @ searchtools.js:99
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:97 
        
        
       GET https://openxr-tutorial.com/undefinedindex.html 404 (Not Found)
_displayItem @ searchtools.js:97
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at Object.htmlToText (searchtools.js:167:53)
    at Object.makeSearchSummary (searchtools.js:553:25)
    at searchtools.js:102:20
htmlToText @ searchtools.js:167
makeSearchSummary @ searchtools.js:553
(anonymous) @ searchtools.js:102
Promise.then (async)
_displayItem @ searchtools.js:99
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:97 
        
        
       GET https://openxr-tutorial.com/undefined6-next-steps.html 404 (Not Found)
_displayItem @ searchtools.js:97
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at Object.htmlToText (searchtools.js:167:53)
    at Object.makeSearchSummary (searchtools.js:553:25)
    at searchtools.js:102:20
htmlToText @ searchtools.js:167
makeSearchSummary @ searchtools.js:553
(anonymous) @ searchtools.js:102
Promise.then (async)
_displayItem @ searchtools.js:99
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:97 
        
        
       GET https://openxr-tutorial.com/undefinedOutlines.html 404 (Not Found)
_displayItem @ searchtools.js:97
_displayNextItem @ searchtools.js:131
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
(anonymous) @ searchtools.js:133
setTimeout (async)
_displayNextItem @ searchtools.js:132
query @ searchtools.js:371
setIndex @ searchtools.js:190
(anonymous) @ searchindex.js:1
searchtools.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at Object.htmlToText (searchtools.js:167:53)
    at Object.makeSearchSummary (searchtools.js:553:25)
    at searchtools.js:102:20
```

**Comment by rvkennedy** [comment]
Ah this is openxr-tutorial.com - may be better to test openxr-tutorial.simul.co for now, I'm not updating the main site until we have everything solid in the new layout.

**Comment by rbessems** [comment]
works on openxr-tutorial.simul.co. Let's leave this open until it works on openxr-tutorial.com though so we don't forget to check at the end.

**Comment by rvkennedy** [comment]
Hmmm. Could be DNS-related.

**Comment by rbessems** [comment]
@rvkennedy FYI This is still an issue

**Comment by rbessems** [comment]
Also search at toplevel should redirect to android/vulkan search, not only search the toplevel page.

**Comment by rvkennedy** [comment]
Fixed. By forcing sphinx to version 6.3.1 and not the latest version, the snippets are shown correctly.
Be sure to clear your browser cache if the issue persists for you.

**Comment by AndrewRichards-Code** [comment]
[v0.5.20](https://github.com/KhronosGroup/OpenXR-Tutorials/releases/tag/v0.5.20) onwards, I am seeing search snippets.

**Comment by rvkennedy** [comment]
Complete. In future if Sphinx must be upgraded, the theme will also need an update to prevent this issue from recurring.
